project_id = "bjeezhrfcyhvnfoxkrbq"

[functions.search-product-price]
verify_jwt = false

[functions.estimate-missing-prices]
verify_jwt = false

[functions.generate-product-image]
verify_jwt = false

[functions.create-paypal-order]
verify_jwt = false

[functions.capture-paypal-order]
verify_jwt = false

[functions.chatbot-assistant]
verify_jwt = false
