project_id = "bjeezhrfcyhvnfoxkrbq"

[functions.setup-telegram-bot]
verify_jwt = false

[functions.notify-manual-assignment]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.notify-deliverers]
verify_jwt = false

[functions.respond-delivery-request]
verify_jwt = false

[functions.report-store]
verify_jwt = false

[functions.search-product-price]
verify_jwt = false

[functions.estimate-missing-prices]
verify_jwt = false

[functions.generate-product-image]
verify_jwt = false

[functions.create-paypal-order]
verify_jwt = false

[functions.capture-paypal-order]
verify_jwt = false

[functions.chatbot-assistant]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.admin-password-recovery]
verify_jwt = false

[functions.notify-service-closure]
verify_jwt = false
